<script setup lang="ts">
import { Capacitor } from '@capacitor/core'
import { App } from '@capacitor/app'
import { loginToken } from './utils/login'
import { checkForUpdate, installUpdate, type Update } from './utils/update'
import { ascentLabel, averageLabel, dateLabel, dayLabel, defaultWallSelection, frenchGrade, gradeChoices, isActive, logKind, score } from './utils/domain'

const { adventureProgress, resetAdventure, state, gyms, activeRoutes, ranked, initialize, connect, refresh, selectGym, selectTab, openRoute, closeRoute, loadLogs, submitAscent, deleteLog, submitGrade, logout, clearSaved } = useTopLogger()
const showFilters = ref(false), search = ref('')
const signingIn = ref(false)
const appVersion = ref('3.0.0')
const update = ref<Update | null>(null), updateStatus = ref<'' | 'checking' | 'current' | 'failed'>('')
const downloading = ref<number | null>(null), downloadError = ref('')
const downloadLabel = computed(() => downloading.value === null ? '' : downloading.value < 0 ? 'Downloading…' : `Downloading… ${downloading.value}%`)
const grade = ref(''), selectedWalls = ref<string[]>([]), color = ref(''), status = ref('')
const wallsChanged = ref(false)
const root = ref<HTMLElement | null>(null), detailHeading = ref<HTMLElement | null>(null)
const tabs = [{ id: 'routes', title: 'Routes' }, { id: 'top', title: 'Top 10' }, { id: 'adventure', title: 'Adventure' }, { id: 'account', title: 'Account' }] as const
const title = computed(() => tabs.find(tab => tab.id === state.tab)?.title || 'Routes')
const source = computed(() => [...activeRoutes.value].sort((a, b) => a.grade - b.grade || (a.wall?.nameLoc || '').localeCompare(b.wall?.nameLoc || '') || (a.label || '').localeCompare(b.label || '', undefined, { numeric: true })))
const filtered = computed(() => source.value.filter(route => {
  const query = search.value.trim().toLowerCase()
  return (!query || [route.name, route.label, route.wall?.nameLoc, route.holdColor?.nameLoc, route.setterName, frenchGrade(route.grade)].some(value => value?.toLowerCase().includes(query)))
    && (!grade.value || String(route.grade) === grade.value) && (!selectedWalls.value.length || selectedWalls.value.includes(route.wall?.nameLoc || ''))
    && (!color.value || route.holdColor?.nameLoc === color.value)
    && (!status.value || (status.value === 'topped' ? (route.climbUser?.tickType || 0) > 0 : status.value === 'todo' ? !route.climbUser?.tickType : status.value === 'attempted' ? (route.climbUser?.totalTries || 0) > 0 && !route.climbUser?.tickType : !route.climbUser?.totalTries && !route.climbUser?.tickType))
}))
const grades = computed(() => [...new Set(activeRoutes.value.map(route => route.grade))].sort((a, b) => a - b))
const walls = computed(() => [...new Set(activeRoutes.value.flatMap(route => route.wall?.nameLoc ? [route.wall.nameLoc] : []))].sort((a, b) => a.localeCompare(b, undefined, { numeric: true })))
const colors = computed(() => [...new Set(activeRoutes.value.map(route => route.holdColor?.nameLoc).filter(Boolean))].sort())
const filterCount = computed(() => [grade.value, selectedWalls.value.length, color.value, status.value].filter(Boolean).length)
const topped = computed(() => activeRoutes.value.filter(route => (route.climbUser?.tickType || 0) > 0).length)
const communityRating = computed(() => {
  const votes = state.community?.ratingVoteStats ?? [], count = votes.reduce((sum, item) => sum + item.count, 0)
  return count ? `${(votes.reduce((sum, item) => sum + item.stars * item.count, 0) / count).toFixed(1)} / 5` : 'No ratings yet'
})
const gradeVotes = computed(() => [...(state.community?.gradeVoteStats ?? [])].filter(vote => vote.count > 0).sort((a, b) => a.grade - b.grade))
const gradeVoteTotal = computed(() => gradeVotes.value.reduce((total, vote) => total + vote.count, 0))
const mostVotedGrades = computed(() => {
  const highest = Math.max(...gradeVotes.value.map(vote => vote.count), 0)
  return gradeVotes.value.filter(vote => vote.count === highest).map(vote => frenchGrade(vote.grade)).join(' / ')
})
const synced = computed(() => {
  const value = state.tab === 'top' ? state.historyAt : state.syncedAt
  return value ? new Date(value).toLocaleString('en-GB', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' }) : ''
})
watch(() => state.gymId, () => { grade.value = ''; selectedWalls.value = []; wallsChanged.value = false; color.value = ''; status.value = ''; search.value = '' })
watch([() => state.gymId, walls], () => {
  if (!wallsChanged.value) selectedWalls.value = defaultWallSelection(gyms.value.find(gym => gym.id === state.gymId)?.name || '', walls.value)
})
function allWalls() { wallsChanged.value = true; selectedWalls.value = [] }
watch(() => state.theme, theme => {
  document.documentElement.dataset.theme = theme
  localStorage.setItem('tlp:theme', theme)
})
async function signIn() {
  signingIn.value = true; state.error = ''
  try { const value = await loginToken(); await connect(value) }
  catch (error) { state.error = error instanceof Error ? error.message : 'Sign-in could not be completed. Please try again.' }
  finally { signingIn.value = false }
}
async function checkUpdates(force = false) {
  if (force) updateStatus.value = 'checking'
  try { update.value = await checkForUpdate(appVersion.value, { force }); if (force) updateStatus.value = update.value ? '' : 'current' }
  catch { if (force) updateStatus.value = 'failed' }
}
async function downloadUpdate() {
  if (!update.value || downloading.value !== null) return
  downloading.value = -1; downloadError.value = ''
  try { await installUpdate(update.value, percent => { downloading.value = percent }) }
  catch (error) { downloadError.value = error instanceof Error ? error.message : 'The update could not be downloaded.' }
  finally { downloading.value = null }
}
// Fallback: leaving the app's origin makes Capacitor hand the link to the default browser app.
function openInBrowser() { if (update.value) window.location.href = update.value.url }
function resetFilters() { grade.value = ''; allWalls(); color.value = ''; status.value = ''; search.value = '' }
async function changeTab(tab: typeof state.tab) { closeRoute(); await selectTab(tab); window.scrollTo({ top: 0 }) }
function showRoute(route: Parameters<typeof openRoute>[0]) {
  history.pushState({ route: route.id }, '')
  void openRoute(route)
  window.scrollTo({ top: 0 }); nextTick(() => detailHeading.value?.focus())
}
function back() {
  if (state.selected) { if (history.state?.route) history.back(); else closeRoute() }
  else if (showFilters.value) showFilters.value = false
  else if (state.tab !== 'routes') void changeTab('routes')
  else if (Capacitor.isNativePlatform()) void App.exitApp()
}
const pullStart = ref<number | null>(null), pullDistance = ref(0)
function touchStart(event: TouchEvent) { pullStart.value = window.scrollY <= 0 && !state.selected && !state.busy && state.tab !== 'account' ? event.touches[0]!.clientY : null }
function touchMove(event: TouchEvent) { pullDistance.value = pullStart.value === null ? 0 : Math.max(0, event.touches[0]!.clientY - pullStart.value) }
function touchEnd() { if (pullDistance.value > 90 && state.connected && !state.needsLogin) void refresh(); pullStart.value = null; pullDistance.value = 0 }
let backHandle: Awaited<ReturnType<typeof App.addListener>> | undefined
const popState = () => closeRoute()
onMounted(async () => {
  window.addEventListener('popstate', popState)
  if (Capacitor.isNativePlatform()) { backHandle = await App.addListener('backButton', back); appVersion.value = (await App.getInfo()).version; void checkUpdates() }
  await initialize()
  document.documentElement.dataset.theme = state.theme
})
onBeforeUnmount(() => { window.removeEventListener('popstate', popState); void backHandle?.remove() })
</script>

<template>
  <div ref="root" class="app-shell max-w-195 min-h-dvh mx-auto [background:linear-gradient(160deg,_var(--panel),_var(--surface)_240px)]" @touchstart.passive="touchStart" @touchmove.passive="touchMove" @touchend.passive="touchEnd">
    <a class="skip-link absolute top-[-100px] left-3 p-3 bg-surface z-[20] [&:focus]:top-3" href="#main">Skip to content</a>
    <header class="app-header flex items-center justify-between gap-3 [padding:calc(6px_+_env(safe-area-inset-top))_16px_6px] min-h-15 border-b border-solid border-b-line max-[420px]:pl-3 max-[420px]:pr-3">
      <a class="brand text-ink no-underline whitespace-nowrap text-[.95rem] font-[650]" href="#" aria-label="TopLogger Plus home" @click.prevent="changeTab('routes')"><span>TopLogger <span class="brand-plus text-accent font-semibold">Plus</span></span></a>
      <label v-if="state.user && gyms.length" class="gym-picker min-w-0 max-w-[48%] [&_select]:min-h-12 [&_select]:max-w-full [&_select]:p-2 [&_select]:bg-transparent [&_select]:border-0 [&_select]:text-ink [&_select]:text-[.8rem] [&_select]:[text-overflow:ellipsis] max-[420px]:[&_select]:text-[.75rem]"><span class="sr-only">Selected gym</span><select aria-label="Selected gym" :value="state.gymId" :disabled="state.ascentBusy" @change="selectGym(($event.target as HTMLSelectElement).value)"><option v-for="gym in gyms" :key="gym.id" :value="gym.id">{{ gym.name }}</option></select></label>
      
    </header>

    <main class="max-w-195 mx-auto [padding:12px_16px_calc(82px_+_env(safe-area-inset-bottom))] max-[420px]:[padding:10px_12px_calc(82px_+_env(safe-area-inset-bottom))] [&.login-main]:max-w-125 [&.login-main]:pt-6" id="main" :class="{ 'login-main': !state.user }">
      <div v-if="state.user" role="status" aria-live="polite" aria-atomic="true"><p v-if="state.adventureMessage" class="notice flex items-center justify-between flex-wrap gap-2.5 p-3 mb-3 bg-soft [border-left:3px_solid_var(--accent)] text-[.8rem] [&.error]:text-error [&.error]:bg-error-bg [&.error]:border-l-error [&_button]:px-3 [&_button]:py-2 [&_button]:border [&_button]:border-solid [&_button]:border-[currentColor] [&_button]:rounded-[3px] [&_button]:text-inherit [&_button]:bg-transparent">{{ state.adventureMessage }}</p></div>
      <p v-if="state.user && state.adventureWarning" class="notice error flex items-center justify-between flex-wrap gap-2.5 p-3 mb-3 bg-soft [border-left:3px_solid_var(--accent)] text-[.8rem] [&.error]:text-error [&.error]:bg-error-bg [&.error]:border-l-error [&_button]:px-3 [&_button]:py-2 [&_button]:border [&_button]:border-solid [&_button]:border-[currentColor] [&_button]:rounded-[3px] [&_button]:text-inherit [&_button]:bg-transparent" role="alert">{{ state.adventureWarning }}</p>
      <div v-if="update" class="notice flex items-center justify-between flex-wrap gap-2.5 p-3 mb-3 bg-soft [border-left:3px_solid_var(--accent)] text-[.8rem] [&.error]:text-error [&.error]:bg-error-bg [&.error]:border-l-error [&_button]:px-3 [&_button]:py-2 [&_button]:border [&_button]:border-solid [&_button]:border-[currentColor] [&_button]:rounded-[3px] [&_button]:text-inherit [&_button]:bg-transparent" :class="{ error: downloadError }" role="status">{{ downloadError || downloadLabel || `Version ${update.version} is available.` }}<span v-if="downloadError" class="flex gap-2"><button @click="downloadUpdate">Retry</button><button @click="openInBrowser">Open in browser</button></span><span v-else-if="downloading === null" class="flex gap-2"><button @click="downloadUpdate">Download</button><button @click="update = null">Later</button></span></div>
      <div v-if="!state.initialized" class="empty-state [padding:32px_8px] text-center text-muted [&>svg]:w-6 [&>svg]:h-6 [&>svg]:mb-3 [&_h1]:text-[.95rem] [&_h1]:text-ink [&_h1]:mb-2 [&_h2]:text-[.95rem] [&_h2]:text-ink [&_h2]:mb-2 [&_p]:max-w-82.5 [&_p]:[margin:0_auto_12px] [&_p]:text-[.8rem]" role="status"><span class="spinner inline-block w-4.5 h-4.5 [border:2px_solid_var(--line)] border-t-accent rounded-full shrink-0 animate-spin" /><h1>Getting things ready</h1><p>Opening your saved connection.</p></div>
      <section v-else-if="!state.user" class="onboarding [&_h1]:text-[1.25rem] [&_h1]:mb-4.5">
        <h1>Connect TopLogger</h1>
        <div class="connect-card">

          <div v-if="state.error" class="notice error flex items-center justify-between flex-wrap gap-2.5 p-3 mb-3 bg-soft [border-left:3px_solid_var(--accent)] text-[.8rem] [&.error]:text-error [&.error]:bg-error-bg [&.error]:border-l-error [&_button]:px-3 [&_button]:py-2 [&_button]:border [&_button]:border-solid [&_button]:border-[currentColor] [&_button]:rounded-[3px] [&_button]:text-inherit [&_button]:bg-transparent" role="alert">{{ state.error }}</div>
          <button v-if="Capacitor.isNativePlatform()" class="primary full flex items-center justify-center gap-2 px-3.5 py-2.5 rounded-[4px] text-[.82rem] font-semibold border border-solid border-[#8d61ef] [background:linear-gradient(180deg,_var(--button-top),_var(--button-bottom))] text-accent-text [box-shadow:inset_0_1px_0_#ffffff20] w-full" :disabled="signingIn || state.busy" @click="signIn"><AppIcon name="connect" />{{ signingIn ? 'Waiting for TopLogger…' : 'Sign in with TopLogger' }}</button>
          <p v-if="!Capacitor.isNativePlatform()" class="muted text-muted">Sign in using the Android app.</p>
          <p class="privacy-note mt-4.5 text-muted text-[.68rem] text-center">{{ Capacitor.isNativePlatform() ? 'Encrypted on your device. No Plus server. No password stored.' : 'Browser preview.' }}</p>
        </div>

      </section>

      <template v-else>
        <div v-if="state.error" class="notice error flex items-center justify-between flex-wrap gap-2.5 p-3 mb-3 bg-soft [border-left:3px_solid_var(--accent)] text-[.8rem] [&.error]:text-error [&.error]:bg-error-bg [&.error]:border-l-error [&_button]:px-3 [&_button]:py-2 [&_button]:border [&_button]:border-solid [&_button]:border-[currentColor] [&_button]:rounded-[3px] [&_button]:text-inherit [&_button]:bg-transparent" role="alert">{{ state.error }}<button v-if="!state.needsLogin" @click="refresh">Retry</button></div>
        <div v-if="state.needsLogin" class="notice flex items-center justify-between flex-wrap gap-2.5 p-3 mb-3 bg-soft [border-left:3px_solid_var(--accent)] text-[.8rem] [&.error]:text-error [&.error]:bg-error-bg [&.error]:border-l-error [&_button]:px-3 [&_button]:py-2 [&_button]:border [&_button]:border-solid [&_button]:border-[currentColor] [&_button]:rounded-[3px] [&_button]:text-inherit [&_button]:bg-transparent" role="status">Reconnect to refresh your data. Saved routes remain available.<button @click="changeTab('account')">Reconnect</button></div>
        <div v-if="state.cacheWarning" class="notice flex items-center justify-between flex-wrap gap-2.5 p-3 mb-3 bg-soft [border-left:3px_solid_var(--accent)] text-[.8rem] [&.error]:text-error [&.error]:bg-error-bg [&.error]:border-l-error [&_button]:px-3 [&_button]:py-2 [&_button]:border [&_button]:border-solid [&_button]:border-[currentColor] [&_button]:rounded-[3px] [&_button]:text-inherit [&_button]:bg-transparent" role="status">{{ state.cacheWarning }}</div>
        <div v-if="pullDistance > 40" class="pull-hint p-2 text-center text-muted text-[.75rem]" role="status">{{ pullDistance > 90 ? 'Release to refresh' : 'Pull to refresh' }}</div>

        <section v-if="state.selected" class="details-view">
          <button class="back-button flex items-center gap-1.25 p-0 mb-1 border-0 bg-transparent text-accent text-[.8rem] [&_svg]:w-4" @click="back"><AppIcon name="back" />Back to {{ title }}</button>
          <div class="detail-hero flex justify-between items-center gap-3 [padding:8px_0_18px] border-b border-solid border-b-line [&_h1]:[margin:6px_0_10px] [&_h1]:text-[1.8rem] [&_h1]:font-[650] [&_h1_span]:block [&_h1_span]:text-[.95rem] [&_h1_span]:mt-0.75"><div><span class="eyebrow text-[.78rem] text-muted">{{ state.selected.wall?.nameLoc || 'ROUTE DETAILS' }}</span><h1 ref="detailHeading" tabindex="-1">{{ frenchGrade(state.selected.grade) }}<span>{{ state.selected.name || (state.selected.label ? `Rope ${state.selected.label}` : 'Route') }}</span></h1><span class="badge topped inline-block px-1.5 py-0.75 text-muted bg-bg border border-solid border-line rounded-[3px] text-[.66rem] font-medium whitespace-nowrap [&.topped]:text-success [&.topped]:bg-success-soft">{{ ascentLabel(state.selected.climbUser?.tickType) }}</span></div><span class="detail-color w-6.5 h-6.5 rounded-full border border-solid border-[#8888] shrink-0" :style="{ background: /^#[a-f\d]{3,8}$/i.test(state.selected.holdColor?.color || '') ? state.selected.holdColor?.color : '#888' }" /></div>
          <div v-if="isActive(state.selected) || state.selected.climbUser?.tickType" class="detail-panel p-3.5 mt-2.5 border border-solid border-line rounded-[7px] bg-panel [&>h2]:mb-3 [&>p]:mb-3 [&>p]:text-[.8rem]">
            <div class="ascent-buttons flex gap-2 [&_button]:flex-1 [&_button]:px-1.5 [&_button]:py-3 [&_button[aria-pressed=true]]:[outline:2px_solid_var(--accent)] [&_button[aria-pressed=true]]:outline-offset-[2px]" aria-label="Log ascent">
              <button v-for="type in [3, 2, 1]" :key="type" class="primary flex items-center justify-center gap-2 px-3.5 py-2.5 rounded-[4px] text-[.82rem] font-semibold border border-solid border-[#8d61ef] [background:linear-gradient(180deg,_var(--button-top),_var(--button-bottom))] text-accent-text [box-shadow:inset_0_1px_0_#ffffff20]" :aria-pressed="state.selected.climbUser?.tickType === type" :disabled="!isActive(state.selected) || state.ascentBusy || state.busy || state.needsLogin || !state.connected || !!state.selected.climbUser?.tickType || (type > 1 && !!state.selected.climbUser?.totalTries) || typeof state.selected.leadEnabled !== 'boolean'" :aria-busy="state.ascentAction === `${state.selected.id}:ascent:${type}`" @click="submitAscent(type)"><span v-if="state.ascentAction === `${state.selected.id}:ascent:${type}`" class="spinner inline-block w-4.5 h-4.5 [border:2px_solid_var(--line)] border-t-accent rounded-full shrink-0 animate-spin" aria-hidden="true" /><AppIcon v-else :name="type === 3 ? 'doubleCheck' : type === 2 ? 'flash' : 'check'" />{{ ascentLabel(type) }}</button>
            </div>
            <div class="try-row flex items-center justify-between gap-3 mt-3 [&_button]:flex-1">
              <button class="secondary flex items-center justify-center gap-2 px-3.5 py-2.5 rounded-[4px] text-[.82rem] font-semibold border border-solid border-line bg-surface" :disabled="!isActive(state.selected) || state.ascentBusy || state.busy || state.needsLogin || !state.connected || typeof state.selected.leadEnabled !== 'boolean'" :aria-busy="state.ascentAction === `${state.selected.id}:ascent:0`" @click="submitAscent(0)"><span v-if="state.ascentAction === `${state.selected.id}:ascent:0`" class="spinner inline-block w-4.5 h-4.5 [border:2px_solid_var(--line)] border-t-accent rounded-full shrink-0 animate-spin" aria-hidden="true" /><AppIcon v-else name="plus" />Try</button>
              <button v-if="state.selected.climbUser?.tickType" class="secondary flex items-center justify-center gap-2 px-3.5 py-2.5 rounded-[4px] text-[.82rem] font-semibold border border-solid border-line bg-surface" :disabled="!isActive(state.selected) || state.ascentBusy || state.busy || state.needsLogin || !state.connected || typeof state.selected.leadEnabled !== 'boolean'" :aria-busy="state.ascentAction === `${state.selected.id}:ascent:repeat`" @click="submitAscent(1)"><span v-if="state.ascentAction === `${state.selected.id}:ascent:repeat`" class="spinner inline-block w-4.5 h-4.5 [border:2px_solid_var(--line)] border-t-accent rounded-full shrink-0 animate-spin" aria-hidden="true" /><AppIcon v-else name="refresh" />Repeat</button>
              <span class="try-count min-w-17.5 text-right text-[.85rem] text-muted [&_strong]:text-ink [&_strong]:text-[1.1rem]" role="status"><strong>{{ state.selected.climbUser?.totalTries || 0 }}</strong> {{ state.selected.climbUser?.totalTries === 1 ? 'try' : 'tries' }}</span>
            </div>
            <button v-if="state.selected.climbUser?.tickType" class="secondary full unsend-button flex items-center justify-center gap-2 px-3.5 py-2.5 rounded-[4px] text-[.82rem] font-semibold border border-solid border-line bg-surface w-full mt-3" :disabled="state.ascentBusy || state.busy || state.needsLogin || !state.connected" :aria-busy="state.ascentAction === `${state.selected.id}:ascent:-1`" @click="submitAscent(-1)"><span v-if="state.ascentAction === `${state.selected.id}:ascent:-1`" class="spinner inline-block w-4.5 h-4.5 [border:2px_solid_var(--line)] border-t-accent rounded-full shrink-0 animate-spin" aria-hidden="true" /><AppIcon v-else name="back" />Unsend</button>
            <template v-if="gradeChoices(state.selected.grade).length">
              <h3 class="grade-vote-title [margin:16px_0_8px]">Your grade</h3>
              <div class="grade-buttons grid [grid-template-columns:repeat(5,_minmax(0,_1fr))] gap-1.5 [&_button]:[padding:12px_2px] [&_button]:relative [&_.button-loading_.button-label]:opacity-[0] [&_.spinner]:absolute [&_.current-grade]:border-accent [&_button[aria-pressed=true]]:bg-accent [&_button[aria-pressed=true]]:text-white [&_button[aria-pressed=true]]:opacity-[1]" role="group" aria-label="Vote on the grade">
                <button v-for="(grade, index) in gradeChoices(state.selected.grade)" :key="index" class="secondary flex items-center justify-center gap-2 px-3.5 py-2.5 rounded-[4px] text-[.82rem] font-semibold border border-solid border-line bg-surface" :class="{ 'current-grade': index === 2, 'button-loading': state.ascentAction === `${state.selected.id}:grade:${grade}` }" :aria-busy="state.ascentAction === `${state.selected.id}:grade:${grade}`" :aria-pressed="grade !== null && state.selected.climbUser?.grade === grade" :disabled="grade === null || state.ascentBusy || state.busy || state.needsLogin || !state.connected || state.selected.climbUser?.grade === grade" @click="grade !== null && submitGrade(grade)"><span class="button-label">{{ grade === null ? '—' : frenchGrade(grade) }}</span><span v-if="state.ascentAction === `${state.selected.id}:grade:${grade}`" class="spinner inline-block w-4.5 h-4.5 [border:2px_solid_var(--line)] border-t-accent rounded-full shrink-0 animate-spin" aria-hidden="true" /></button>
              </div>
            </template>
            <div v-if="state.ascentError" class="notice error flex items-center justify-between flex-wrap gap-2.5 p-3 mb-3 bg-soft [border-left:3px_solid_var(--accent)] text-[.8rem] [&.error]:text-error [&.error]:bg-error-bg [&.error]:border-l-error [&_button]:px-3 [&_button]:py-2 [&_button]:border [&_button]:border-solid [&_button]:border-[currentColor] [&_button]:rounded-[3px] [&_button]:text-inherit [&_button]:bg-transparent" role="alert">{{ state.ascentError }}</div>
          </div>
          <div class="detail-panel p-3.5 mt-2.5 border border-solid border-line rounded-[7px] bg-panel [&>h2]:mb-3 [&>p]:mb-3 [&>p]:text-[.8rem]"><div class="section-heading flex justify-between items-center gap-3 mb-3"><h2>Your log</h2><span v-if="state.logsBusy" class="spinner inline-block w-4.5 h-4.5 [border:2px_solid_var(--line)] border-t-accent rounded-full shrink-0 animate-spin" aria-label="Loading your log" /></div>
            <div v-if="state.logsError" class="notice error flex items-center justify-between flex-wrap gap-2.5 p-3 mb-3 bg-soft [border-left:3px_solid_var(--accent)] text-[.8rem] [&.error]:text-error [&.error]:bg-error-bg [&.error]:border-l-error [&_button]:px-3 [&_button]:py-2 [&_button]:border [&_button]:border-solid [&_button]:border-[currentColor] [&_button]:rounded-[3px] [&_button]:text-inherit [&_button]:bg-transparent" role="alert">{{ state.logsError }}<button :disabled="state.logsBusy" @click="loadLogs(state.selected.id)">Retry</button></div>
            <p v-if="state.logs && !state.logs.length" class="muted text-muted">No logs yet.</p>
            <ul v-else-if="state.logs" class="route-logs list-none p-0 m-0 [&_li]:flex [&_li]:items-center [&_li]:gap-3 [&_li]:px-0 [&_li]:py-1.5 [&_li]:border-t [&_li]:border-solid [&_li]:border-t-line [&_li]:text-[.8rem]" aria-label="Your log">
              <li v-for="log in state.logs" :key="log.id"><span class="w-20 shrink-0 text-muted">{{ dayLabel(log.climbedAtDate) }}</span><span class="flex-1 min-w-0 [overflow-wrap:anywhere]"><strong :class="{ 'text-success': log.topped }">{{ logKind(log) }}</strong><span v-if="state.selected.leadEnabled && !state.selected.leadRequired && typeof log.lead === 'boolean'" class="muted text-muted"> · {{ log.lead ? 'Lead' : 'Toprope' }}</span></span><button class="secondary flex items-center justify-center gap-2 min-h-12 px-3 rounded-[4px] text-[.75rem] font-semibold border border-solid border-line bg-surface text-error" :disabled="state.ascentBusy || state.busy || state.needsLogin || !state.connected" :aria-busy="state.ascentAction === `${state.selected.id}:log:${log.id}`" :aria-label="`Delete ${logKind(log)} from ${dayLabel(log.climbedAtDate)}`" @click="deleteLog(log)"><span v-if="state.ascentAction === `${state.selected.id}:log:${log.id}`" class="spinner inline-block w-4.5 h-4.5 [border:2px_solid_var(--line)] border-t-accent rounded-full shrink-0 animate-spin" aria-hidden="true" /><span v-else>Delete</span></button></li>
            </ul>
          </div>
          <div class="detail-panel p-3.5 mt-2.5 border border-solid border-line rounded-[7px] bg-panel [&>h2]:mb-3 [&>p]:mb-3 [&>p]:text-[.8rem]"><h2>Route</h2><dl class="detail-grid grid grid-cols-2 [gap:14px_18px] m-0 [&_dt]:text-muted [&_dt]:text-[.72rem] [&_dt]:mb-0.75 [&_dd]:m-0 [&_dd]:text-[.85rem] [&_dd]:font-medium [&_dd]:[overflow-wrap:anywhere]"><div><dt>Wall</dt><dd>{{ state.selected.wall?.nameLoc || 'Unknown' }}</dd></div><div><dt>Rope / label</dt><dd>{{ state.selected.label || '—' }}</dd></div><div><dt>Hold color</dt><dd>{{ state.selected.holdColor?.nameLoc || 'Unknown' }}</dd></div><div><dt>Setter</dt><dd>{{ [...(state.selected.climbSetters || []).map(setter => setter.gymAdmin.name), ...(state.selected.setterName ? [state.selected.setterName] : [])].join(', ') || 'Unknown' }}</dd></div><div><dt>Set on</dt><dd>{{ dateLabel(state.selected.inAt) }}</dd></div><div><dt>Leaving / removed</dt><dd>{{ dateLabel(state.selected.outAt || state.selected.outPlannedAt) }}</dd></div></dl></div>
          <div class="detail-panel p-3.5 mt-2.5 border border-solid border-line rounded-[7px] bg-panel [&>h2]:mb-3 [&>p]:mb-3 [&>p]:text-[.8rem]"><h2>Your ascents</h2><dl class="detail-grid grid grid-cols-2 [gap:14px_18px] m-0 [&_dt]:text-muted [&_dt]:text-[.72rem] [&_dt]:mb-0.75 [&_dd]:m-0 [&_dd]:text-[.85rem] [&_dd]:font-medium [&_dd]:[overflow-wrap:anywhere]"><div><dt>Attempts</dt><dd>{{ state.selected.climbUser?.totalTries || 0 }}</dd></div><div><dt>Best ascent</dt><dd>{{ ascentLabel(state.selected.climbUser?.tickType) }}</dd></div><div><dt>Your grade</dt><dd>{{ frenchGrade(state.selected.climbUser?.grade) }}</dd></div><div><dt>Score</dt><dd>{{ score(state.selected.grade, state.selected.climbUser?.tickType || 0) ?? '—' }}</dd></div><div><dt>First attempt</dt><dd>{{ dateLabel(state.selected.climbUser?.triedFirstAtDate) }}</dd></div><div><dt>First top</dt><dd>{{ dateLabel(state.selected.climbUser?.tickedFirstAtDate) }}</dd></div></dl></div>
          <div class="detail-panel p-3.5 mt-2.5 border border-solid border-line rounded-[7px] bg-panel [&>h2]:mb-3 [&>p]:mb-3 [&>p]:text-[.8rem]"><div class="section-heading flex justify-between items-center gap-3 [margin:16px_0_4px] [&_.muted]:text-[.72rem]"><h2>Community</h2><span v-if="state.communityBusy" class="spinner inline-block w-4.5 h-4.5 [border:2px_solid_var(--line)] border-t-accent rounded-full shrink-0 animate-spin" aria-label="Loading community data" /></div><div v-if="state.communityError" class="notice error flex items-center justify-between flex-wrap gap-2.5 p-3 mb-3 bg-soft [border-left:3px_solid_var(--accent)] text-[.8rem] [&.error]:text-error [&.error]:bg-error-bg [&.error]:border-l-error [&_button]:px-3 [&_button]:py-2 [&_button]:border [&_button]:border-solid [&_button]:border-[currentColor] [&_button]:rounded-[3px] [&_button]:text-inherit [&_button]:bg-transparent" role="alert">{{ state.communityError }}<button @click="openRoute(state.selected!)">Retry</button></div><template v-if="state.community"><h3>Grade votes</h3>
            <template v-if="gradeVoteTotal">
              <div class="grade-vote-summary flex items-baseline flex-wrap gap-2 mb-3 [&_>_strong]:text-[1.35rem] [&_>_span]:text-muted [&_>_span]:text-[.75rem]"><strong>{{ mostVotedGrades }}</strong><span>Most voted · {{ gradeVoteTotal }} {{ gradeVoteTotal === 1 ? 'vote' : 'votes' }}</span></div>
              <ul class="grade-vote-list [&_li.your-grade-vote_.grade-vote-track>span]:bg-accent list-none p-0 m-0 [&_li]:px-0 [&_li]:py-2.5 [&_li]:border-t [&_li]:border-solid [&_li]:border-t-line" aria-label="Community grade votes">
                <li v-for="vote in gradeVotes" :key="vote.grade" :class="{ 'your-grade-vote': vote.grade === state.selected.climbUser?.grade }">
                  <div class="grade-vote-label flex items-center flex-wrap gap-2 mb-1.5 [&_>_strong]:text-[.95rem]"><strong>{{ frenchGrade(vote.grade) }}</strong><span v-if="vote.grade === state.selected.grade" class="grade-vote-tag [padding:2px_5px] bg-soft text-muted rounded-[3px] text-[.65rem] [&.your-vote-tag]:bg-accent [&.your-vote-tag]:text-accent-text">Route grade</span><span v-if="vote.grade === state.selected.climbUser?.grade" class="grade-vote-tag your-vote-tag [padding:2px_5px] bg-soft text-muted rounded-[3px] text-[.65rem] [&.your-vote-tag]:bg-accent [&.your-vote-tag]:text-accent-text">Your vote</span></div>
                  <div class="grade-vote-result flex items-center flex-wrap gap-2.5"><span class="grade-vote-track flex-1 min-w-20 h-2.5 rounded-[3px] bg-soft overflow-hidden [&_>_span]:block [&_>_span]:h-[100%] [&_>_span]:bg-muted [&_>_span]:rounded-[inherit]" aria-hidden="true"><span :style="{ width: `${vote.count / gradeVoteTotal * 100}%` }" /></span><span class="grade-vote-count text-[.75rem] tabular-nums"><strong>{{ vote.count }}</strong> {{ vote.count === 1 ? 'vote' : 'votes' }} <span class="muted text-muted">· {{ Math.round(vote.count / gradeVoteTotal * 100) }}%</span></span></div>
                </li>
              </ul>
            </template>
            <p v-else class="muted text-muted">No grade votes yet.</p>
            <p v-if="state.selected.climbUser?.grade" class="grade-personal-vote pt-2.5 text-muted text-[.75rem]">Your vote: <strong>{{ frenchGrade(state.selected.climbUser.grade) }}</strong></p>
            <h3>Rating <span class="muted text-muted">{{ communityRating }}</span></h3><div class="rating-row flex items-center gap-2.5 [margin:8px_0] text-muted text-[.75rem] [&_meter]:flex-1" v-for="vote in state.community.ratingVoteStats" :key="vote.stars"><span>{{ vote.stars }} stars</span><meter :value="vote.count" :max="Math.max(...state.community.ratingVoteStats.map(item => item.count), 1)" :aria-label="`${vote.count} votes for ${vote.stars} stars`" /><span>{{ vote.count }}</span></div><h3>Toppers</h3><p v-if="state.community.toppersUnavailable" class="muted text-muted">TopLogger has not made the toppers list available.</p><p v-else-if="!state.community.toppers.length" class="muted text-muted">No public tops yet.</p><ul v-else class="toppers list-none p-0 [&_li]:flex [&_li]:items-center [&_li]:gap-2 [&_li]:flex-wrap [&_li]:px-0 [&_li]:py-2.5 [&_li]:border-t [&_li]:border-solid [&_li]:border-t-line [&_li]:text-[.8rem] [&_svg]:w-4 [&_svg]:text-accent [&_.muted]:text-[.72rem] [&_.muted]:ml-auto"><li v-for="topper in state.community.toppers" :key="topper.id"><AppIcon name="check" /><span>{{ topper.user?.fullName || 'Anonymous climber' }}</span><span class="muted text-muted">{{ ascentLabel(topper.tickType) }}<template v-if="topper.grade"> · {{ frenchGrade(topper.grade) }}</template></span></li></ul></template></div>
        </section>

        <section v-else-if="state.tab === 'adventure'">
          <div class="page-heading flex justify-between items-center gap-3 mb-2"><h1>Adventure</h1></div>
          <div class="detail-panel adventure-level p-3.5 mt-2.5 border border-solid border-line rounded-[7px] bg-panel [&>h2]:mb-3 [&>p]:mb-3 [&>p]:text-[.8rem] [&_progress]:w-full [&_progress]:h-4 [&_progress]:accent-accent"><span class="section-kicker text-muted text-[.78rem] font-normal">Your climbing adventure</span><h2>Level {{ adventureProgress.level }}</h2><p>{{ adventureProgress.xp }} total XP · {{ adventureProgress.sends }} rewarded sends</p><progress :value="adventureProgress.currentXp" :max="500" aria-label="XP toward next level" /><p class="muted text-muted">{{ adventureProgress.currentXp }} / 500 XP toward level {{ adventureProgress.level + 1 }}</p></div>
          <div class="detail-panel p-3.5 mt-2.5 border border-solid border-line rounded-[7px] bg-panel [&>h2]:mb-3 [&>p]:mb-3 [&>p]:text-[.8rem]"><h2>Achievements</h2><p class="muted text-muted">Every milestone leads to another. Keep climbing to unlock higher targets.</p><ul class="achievement-list list-none p-0 m-0 [&_li]:flex [&_li]:items-center [&_li]:gap-3 [&_li]:px-0 [&_li]:py-3.5 [&_li]:border-t [&_li]:border-solid [&_li]:border-t-line [&_svg]:w-6 [&_svg]:shrink-0 [&_svg]:text-accent [&_li_>_div]:flex-1 [&_li_>_div]:min-w-0 [&_p]:mx-0 [&_p]:mb-0 [&_p]:mt-1 [&_progress]:w-full [&_progress]:h-2 [&_progress]:mt-2 [&_progress]:accent-accent"><li v-for="item in adventureProgress.achievements" :key="item.id"><AppIcon :name="item.unlocked ? 'check' : 'mountain'" /><div><strong>{{ item.name }}</strong><p class="muted text-muted">{{ item.description }}</p><template v-if="!item.unlocked"><progress :value="item.current" :max="item.target" :aria-label="`${item.name} progress`" /><p class="muted text-muted">{{ item.current.toLocaleString() }} / {{ item.target.toLocaleString() }}</p></template></div><span class="badge inline-block px-1.5 py-0.75 text-muted bg-bg border border-solid border-line rounded-[3px] text-[.66rem] font-medium whitespace-nowrap [&.topped]:text-success [&.topped]:bg-success-soft" :class="{ topped: item.unlocked }">{{ item.unlocked ? 'Unlocked' : 'Locked' }}</span></li></ul></div>
          <div class="detail-panel p-3.5 mt-2.5 border border-solid border-line rounded-[7px] bg-panel [&>h2]:mb-3 [&>p]:mb-3 [&>p]:text-[.8rem]"><h2>How XP works</h2><p class="muted text-muted">New sends logged here earn 100 XP for Redpoint, 125 for Flash, or 150 for Onsight. Each route counts once. Unsend removes its reward. Attempts and grade votes earn no XP.</p><p class="muted text-muted">Progress belongs to this account across all gyms, on this device only. Clearing offline data and signing out keep your adventure.</p><button class="danger full flex items-center justify-center gap-2 px-3.5 py-2.5 rounded-[4px] text-[.82rem] font-semibold border border-solid border-line text-error bg-surface mt-4 w-full" :disabled="state.ascentBusy" @click="resetAdventure">Reset adventure progress</button></div>
        </section>

        <section v-else-if="state.tab === 'account'">
          <div class="page-heading flex justify-between items-center gap-3 mb-2"><div><h1>Account</h1></div></div>
          <div class="profile-card flex items-center flex-wrap gap-3 p-4 border border-solid border-line rounded-[7px] bg-panel [&>div]:flex-1 [&_p]:text-muted [&_p]:text-[.78rem] [&_p]:mt-0.75"><span class="avatar grid place-items-center w-10 h-10 bg-soft text-accent border border-solid border-accent rounded-full text-[1rem]">{{ state.user.fullName?.slice(0, 1) || '?' }}</span><div><h2>{{ state.user.fullName }}</h2><p>{{ gyms.find(gym => gym.id === state.gymId)?.name || 'No gym selected' }}</p></div><span class="badge inline-block px-1.5 py-0.75 text-muted bg-bg border border-solid border-line rounded-[3px] text-[.66rem] font-medium whitespace-nowrap [&.topped]:text-success [&.topped]:bg-success-soft" :class="{ topped: !state.needsLogin }">{{ state.needsLogin ? 'Reconnect' : 'Connected' }}</span></div>
          <div v-if="state.needsLogin" class="detail-panel p-3.5 mt-2.5 border border-solid border-line rounded-[7px] bg-panel [&>h2]:mb-3 [&>p]:mb-3 [&>p]:text-[.8rem]"><h2>Reconnect TopLogger</h2><button v-if="Capacitor.isNativePlatform()" class="primary full flex items-center justify-center gap-2 px-3.5 py-2.5 rounded-[4px] text-[.82rem] font-semibold border border-solid border-[#8d61ef] [background:linear-gradient(180deg,_var(--button-top),_var(--button-bottom))] text-accent-text [box-shadow:inset_0_1px_0_#ffffff20] w-full" :disabled="signingIn || state.busy" @click="signIn">{{ signingIn ? 'Waiting for TopLogger…' : 'Sign in with TopLogger' }}</button><p v-else class="muted text-muted">Sign in using the Android app.</p></div>
          <div class="detail-panel p-3.5 mt-2.5 border border-solid border-line rounded-[7px] bg-panel [&>h2]:mb-3 [&>p]:mb-3 [&>p]:text-[.8rem]"><h2>Appearance</h2><div class="segmented flex gap-1 p-0.75 border border-solid border-line rounded-[7px] bg-bg mb-3 [&_button]:flex [&_button]:items-center [&_button]:justify-center [&_button]:gap-1.5 [&_button]:flex-1 [&_button]:min-w-0 [&_button]:px-1 [&_button]:py-2 [&_button]:border-0 [&_button]:[border-bottom:2px_solid_transparent] [&_button]:bg-transparent [&_button]:text-muted [&_button]:text-[.78rem] [&_button]:rounded-[4px] [&_button[aria-pressed=true]]:border-b-accent [&_button[aria-pressed=true]]:bg-soft [&_button[aria-pressed=true]]:text-ink [&_button[aria-pressed=true]]:font-[650] [&.period]:mb-[0]"><button v-for="theme in (['system', 'light', 'dark'] as const)" :key="theme" :aria-pressed="state.theme === theme" @click="state.theme = theme">{{ theme[0]!.toUpperCase() + theme.slice(1) }}</button></div></div>
          <div class="detail-panel p-3.5 mt-2.5 border border-solid border-line rounded-[7px] bg-panel [&>h2]:mb-3 [&>p]:mb-3 [&>p]:text-[.8rem]"><h2>Saved data</h2><p class="muted text-muted">Clear offline data. Keep your login and adventure progress.</p><button class="secondary full flex items-center justify-center gap-2 px-3.5 py-2.5 rounded-[4px] text-[.82rem] font-semibold border border-solid border-line bg-surface w-full" :disabled="state.busy || state.ascentBusy" @click="clearSaved">Clear saved data</button></div>
          <button class="danger full flex items-center justify-center gap-2 px-3.5 py-2.5 rounded-[4px] text-[.82rem] font-semibold border border-solid border-line text-error bg-surface mt-4 w-full" :disabled="state.ascentBusy" @click="logout">Sign out and clear offline data</button><p class="muted text-muted">Adventure progress stays on this device after signing out.</p><p class="account-footer mt-5 text-center text-muted text-[.68rem]">TopLogger Plus {{ appVersion }}<span v-if="update" role="status"> · Version {{ update.version }} available</span><span v-else-if="updateStatus === 'current'" role="status"> · Up to date</span><span v-else-if="updateStatus === 'failed'" role="status"> · Could not reach GitHub</span></p><button v-if="update" class="block min-h-12 mx-auto px-3 border-0 bg-transparent text-accent text-[.75rem] underline" :disabled="downloading !== null" @click="downloadUpdate">{{ downloadLabel || 'Download update' }}</button><button v-else-if="Capacitor.isNativePlatform()" class="block min-h-12 mx-auto px-3 border-0 bg-transparent text-accent text-[.75rem] underline" :disabled="updateStatus === 'checking'" @click="checkUpdates(true)">{{ updateStatus === 'checking' ? 'Checking…' : 'Check for updates' }}</button>
        </section>

        <section v-else>
          <div class="page-heading flex justify-between items-center gap-3 mb-2"><div><h1>{{ title }}</h1></div><button class="icon-button grid place-items-center w-12 shrink-0 bg-transparent border-0 rounded-[4px] [&:hover]:bg-soft" aria-label="Refresh TopLogger data" :disabled="state.busy || state.needsLogin" @click="refresh"><span v-if="state.busy" class="spinner inline-block w-4.5 h-4.5 [border:2px_solid_var(--line)] border-t-accent rounded-full shrink-0 animate-spin" /><AppIcon v-else name="refresh" /></button></div>
          <template v-if="state.tab === 'top'">
            <div class="segmented period flex gap-1 p-0.75 border border-solid border-line rounded-[7px] bg-bg mb-3 [&_button]:flex [&_button]:items-center [&_button]:justify-center [&_button]:gap-1.5 [&_button]:flex-1 [&_button]:min-w-0 [&_button]:px-1 [&_button]:py-2 [&_button]:border-0 [&_button]:[border-bottom:2px_solid_transparent] [&_button]:bg-transparent [&_button]:text-muted [&_button]:text-[.78rem] [&_button]:rounded-[4px] [&_button[aria-pressed=true]]:border-b-accent [&_button[aria-pressed=true]]:bg-soft [&_button[aria-pressed=true]]:text-ink [&_button[aria-pressed=true]]:font-[650] [&.period]:mb-[0]"><button v-for="days in [60, 120, 180]" :key="days" :aria-pressed="state.days === days" @click="state.days = days">{{ days / 30 }} months</button></div>
            <div class="progress-card p-4 mt-3 border border-solid border-line rounded-[7px] bg-panel [&>div]:grid [&>div]:[grid-template-columns:auto_1fr] [&>div]:items-baseline [&>div]:[gap:5px_12px] [&_strong]:text-[1.35rem] [&_strong]:font-[650] [&_strong]:text-gold [&_span:last-child]:col-span-full [&_span:last-child]:text-muted [&_span:last-child]:text-[.72rem]"><div><span class="section-kicker text-muted text-[.78rem] font-normal">Average</span><strong>{{ state.historyReady ? averageLabel(ranked) : '—' }}</strong><span>{{ state.historyReady ? `${ranked.length} ${ranked.length === 1 ? 'route' : 'routes'} · past ${state.days} days` : state.busy ? 'Loading ascent history…' : 'Ascent history unavailable' }}</span></div></div>
            <div v-if="state.historyError" class="notice error flex items-center justify-between flex-wrap gap-2.5 p-3 mb-3 bg-soft [border-left:3px_solid_var(--accent)] text-[.8rem] [&.error]:text-error [&.error]:bg-error-bg [&.error]:border-l-error [&_button]:px-3 [&_button]:py-2 [&_button]:border [&_button]:border-solid [&_button]:border-[currentColor] [&_button]:rounded-[3px] [&_button]:text-inherit [&_button]:bg-transparent" role="alert">{{ state.historyError }}<button :disabled="state.busy || state.needsLogin" @click="refresh">Retry</button></div>
            <div class="section-heading flex justify-between items-center gap-3 [margin:16px_0_4px] [&_.muted]:text-[.72rem]"><h2>Best ascents</h2><span class="muted text-muted">{{ ranked.length }} / 10</span></div>
            <RouteCard v-for="(item, index) in ranked" :key="item.route.id" :route="item.route" :rank="index + 1" :ranked="item" @open="showRoute" />
            <div v-if="!ranked.length" class="empty-state [padding:32px_8px] text-center text-muted [&>svg]:w-6 [&>svg]:h-6 [&>svg]:mb-3 [&_h1]:text-[.95rem] [&_h1]:text-ink [&_h1]:mb-2 [&_h2]:text-[.95rem] [&_h2]:text-ink [&_h2]:mb-2 [&_p]:max-w-82.5 [&_p]:[margin:0_auto_12px] [&_p]:text-[.8rem]" role="status"><AppIcon name="top" /><h2>{{ state.busy ? 'Loading history' : state.historyReady ? 'No ascents in this period' : 'Ascent history unavailable' }}</h2><p>{{ state.busy ? 'Including routes that have left the wall.' : state.historyReady ? 'No qualifying ascents in this period. Try a longer window.' : 'Connect and refresh to load verified ascent history.' }}</p></div>
            <details class="scoring-note mt-4 text-muted text-[.75rem] [&_summary]:min-h-12 [&_summary]:[padding:12px_0] [&_summary]:cursor-pointer"><summary>Scoring</summary><p>Redpoint: route grade. Flash: grade + 10. Onsight: grade + 15. Your best qualifying ascent per route counts, including removed routes. Ties favor the most recent ascent. The average uses the routes available, up to ten.</p></details>
          </template>
          <template v-else>
            <div v-if="state.tab === 'routes'" class="route-tabs flex gap-1 p-0.75 border border-solid border-line rounded-[7px] bg-bg mb-3 [&_button]:flex [&_button]:items-center [&_button]:justify-center [&_button]:gap-1.5 [&_button]:flex-1 [&_button]:min-w-0 [&_button]:px-1 [&_button]:py-2 [&_button]:border-0 [&_button]:[border-bottom:2px_solid_transparent] [&_button]:bg-transparent [&_button]:text-muted [&_button]:text-[.78rem] [&_button]:rounded-[4px] [&_button[aria-pressed=true]]:border-b-accent [&_button[aria-pressed=true]]:bg-soft [&_button[aria-pressed=true]]:text-ink [&_button[aria-pressed=true]]:font-[650] [&_button_span]:text-[.7rem] [&_button_span]:tabular-nums [&_svg]:w-3.75 [&_svg]:h-3.75" aria-label="Route completion"><button :aria-pressed="!status" @click="status = ''">All <span>{{ activeRoutes.length }}</span></button><button :aria-pressed="status === 'todo'" @click="status = 'todo'">To do <span>{{ activeRoutes.length - topped }}</span></button><button :aria-pressed="status === 'topped'" @click="status = 'topped'"><AppIcon name="check" />Done <span>{{ topped }}</span></button></div>
            <div class="search-row flex gap-2 mb-2"><label class="search flex items-center gap-2 flex-1 min-w-0 [padding:0_10px] border border-solid border-line rounded-[4px] bg-bg [&_svg]:w-4.5 [&_svg]:h-4.5 [&_svg]:text-muted [&_svg]:shrink-0 [&_input]:w-full [&_input]:min-w-0 [&_input]:min-h-12 [&_input]:px-0 [&_input]:py-2 [&_input]:bg-transparent [&_input]:border-0 [&_input]:text-ink [&_input]:text-[.82rem]"><AppIcon name="search" /><input v-model="search" type="search" placeholder="Search" aria-label="Search routes"></label><button class="filter-button flex items-center justify-center gap-1.5 px-3 py-2 border border-solid border-line rounded-[4px] bg-transparent text-[.78rem] max-[420px]:[&_span]:hidden" aria-label="Filters" :aria-expanded="showFilters" aria-controls="filters" @click="showFilters = !showFilters"><AppIcon name="filter" /><span>Filters<template v-if="filterCount"> · {{ filterCount }}</template></span></button></div>
            <div v-if="showFilters" id="filters" class="filters grid grid-cols-2 gap-3 p-3 mb-3 bg-bg border border-solid border-line [&_label]:flex [&_label]:flex-col [&_label]:gap-1.5 [&_label]:text-[.75rem] [&_label]:font-semibold [&_select]:w-full [&_select]:min-w-0 [&_select]:min-h-12 [&_select]:p-2 [&_select]:border [&_select]:border-solid [&_select]:border-line [&_select]:rounded-[3px] [&_select]:bg-surface [&_select]:text-ink [&_.wall-options_label]:flex [&_.wall-options_label]:flex-row [&_.wall-options_label]:items-center [&_.wall-options_label]:gap-1.75 [&_.wall-options_label]:min-h-12 [&_.wall-options_label]:p-1 [&_.wall-options_label]:font-normal"><label>Grade<select v-model="grade" aria-label="Grade"><option value="">All grades</option><option v-for="value in grades" :key="value" :value="String(value)">{{ frenchGrade(value) }}</option></select></label><fieldset class="wall-filter col-span-full min-w-0 m-0 p-0 border-0 [&_legend]:p-0 [&_legend]:text-[.75rem] [&_legend]:font-semibold"><legend>Walls</legend><button class="text-button px-0 py-2 bg-transparent border-0 text-accent text-[.78rem] text-left" :aria-pressed="!selectedWalls.length" @click="allWalls">All walls</button><div class="wall-options flex flex-wrap [gap:4px_12px] [&_input]:w-4.5 [&_input]:h-4.5 [&_input]:m-0 [&_input]:accent-accent"><label v-for="value in walls" :key="value"><input v-model="selectedWalls" type="checkbox" :value="value" @change="wallsChanged = true"><span>{{ value }}</span></label></div></fieldset><label>Hold color<select v-model="color" aria-label="Hold color"><option value="">All colors</option><option v-for="value in colors" :key="value!" :value="value">{{ value }}</option></select></label><label>Ascent status<select v-model="status" aria-label="Ascent status"><option value="">Any status</option><option value="untried">To try</option><option value="attempted">Attempted</option><option value="todo">Not done</option><option value="topped">Done</option></select></label><button class="text-button px-0 py-2 bg-transparent border-0 text-accent text-[.78rem] text-left" @click="resetFilters">Reset filters</button></div>
            <div class="list-count muted text-[.72rem] [padding:6px_0_9px] border-b border-solid border-b-line text-muted"><span v-if="selectedWalls.length">{{ selectedWalls[0] }}<template v-if="selectedWalls.length > 1"> +{{ selectedWalls.length - 1 }}</template> · </span>{{ filtered.length }} {{ filtered.length === 1 ? 'route' : 'routes' }}</div>
            <RouteCard v-for="route in filtered" :key="route.id" :route="route" @open="showRoute" />
            <div v-if="!filtered.length" class="empty-state [padding:32px_8px] text-center text-muted [&>svg]:w-6 [&>svg]:h-6 [&>svg]:mb-3 [&_h1]:text-[.95rem] [&_h1]:text-ink [&_h1]:mb-2 [&_h2]:text-[.95rem] [&_h2]:text-ink [&_h2]:mb-2 [&_p]:max-w-82.5 [&_p]:[margin:0_auto_12px] [&_p]:text-[.8rem]" role="status"><AppIcon name="routes" /><h2>{{ state.busy ? 'Loading routes' : search || filterCount ? 'No matching routes' : 'No routes to show' }}</h2><p>{{ state.busy ? 'Fetching the latest from TopLogger.' : search || filterCount ? 'Try a broader search or clear your filters.' : !state.gymId ? 'Choose a gym in TopLogger, then reconnect here.' : 'Refresh to load the routes at this gym.' }}</p><button v-if="search || filterCount" class="secondary flex items-center justify-center gap-2 px-3.5 py-2.5 rounded-[4px] text-[.82rem] font-semibold border border-solid border-line bg-surface" @click="resetFilters">Clear filters</button></div>
          </template>
          <div class="sync-footer flex justify-start items-center flex-wrap gap-1.5 [margin:18px_0_4px] text-muted text-[.68rem]" role="status"><span class="w-1 h-1 rounded-full bg-muted [&.busy]:bg-accent" :class="['sync-dot', { busy: state.busy }]" />{{ state.busy ? 'Syncing with TopLogger…' : synced ? `Last synced ${synced}` : 'Not synced yet' }}<span v-if="state.historyError && state.tab === 'top' && state.historyReady"> · Saved history</span></div>
        </section>
      </template>
    </main>
    <nav v-if="state.user" class="bottom-nav fixed left-[50%] bottom-[0] [transform:translateX(-50%)] flex w-full max-w-195 [padding:4px_8px_env(safe-area-inset-bottom)] bg-panel border-t border-solid border-t-line z-[10] [&_button]:flex [&_button]:items-center [&_button]:justify-center [&_button]:flex-col [&_button]:gap-0.75 [&_button]:flex-1 [&_button]:min-h-14.5 [&_button]:[padding:7px_2px] [&_button]:border-0 [&_button]:[border-top:2px_solid_transparent] [&_button]:bg-transparent [&_button]:text-muted [&_button]:text-[.65rem] [&_button[aria-current=page]]:[border-top-color:transparent] [&_button[aria-current=page]]:text-accent [&_button[aria-current=page]]:font-semibold [&_button[aria-current=page]]:bg-soft [&_button[aria-current=page]]:rounded-[7px] [&_svg]:w-5 [&_svg]:h-5" aria-label="Main navigation"><button v-for="tab in tabs" :key="tab.id" :aria-current="state.tab === tab.id ? 'page' : undefined" @click="changeTab(tab.id)"><AppIcon :name="tab.id" /><span>{{ tab.title }}</span></button></nav>
  </div>
</template>
